### ISSUE TITLE
Edge detection 결과 이상현상

### ISSUE THREAD

**Issue by nusgnojkrap** [A-big-fish-in-a-small-pond/face-recognition#1]
1) height 의 비율이 input image 와 다름

2) edge detection 는 되는 것으로 보여지나, 정확한 결과가 아님 (물체가 1개에서 3개로 출력됨)

**Comment by libtv** [comment]
원본 파일 :
<img src="https://github.com/A-big-fish-in-a-small-pond/face-recognition/blob/master/image/sample2_err.png?raw=true" width="40%">

결과 파일 :
<img src="https://github.com/A-big-fish-in-a-small-pond/face-recognition/blob/master/image/sample2_result_err.png?raw=true" width="40%">

**Comment by nusgnojkrap** [comment]
해결
